import {
  anonymousFunction,
  arrayDest1,
  arrayDest2,
  arrayDest3,
  arrayMap,
  arraySpread,
  fatArrowFunction,
  fatArrowFunction2,
  fatArrowFunction3,
  fatArrowFunctionShort,
  normalFunction,
  normalFunction2,
  objectDest1,
  objectDest2,
  objectDest3,
  objectSpread,
  promise1,
  promise2,
  promise3,
  switchStatement,
  tern1,
  tern2,
} from '@/slides/Introduction/code-examples/code-surfer.ts';

export const steps = [
  {
    code: normalFunction,
    title: 'Functions',
    subtitle: 'Normal function (named)',
    lang: 'js',
    showNumbers: true,
  },
  {
    code: normalFunction2,
    title: 'Functions',
    subtitle: 'Normal function (named)',
    lang: 'js',
    showNumbers: true,
  },
  {
    code: anonymousFunction,
    title: 'Functions',
    subtitle: 'Normal function (anonymous inline definition)',
    lang: 'js',
    showNumbers: true,
    focus: '1[25:37],2,3[1]',
  },
  {
    code: fatArrowFunction,
    title: 'Functions',
    subtitle: 'Fat arrow function',
    lang: 'js',
    showNumbers: true,
    focus: '1:3',
  },
  {
    code: fatArrowFunction2,
    title: 'Functions',
    subtitle: 'Fat arrow function',
    lang: 'js',
    showNumbers: true,
  },
  {
    code: fatArrowFunctionShort,
    title: 'Functions',
    subtitle: 'Fat arrow function (short syntax)',
    lang: 'js',
    showNumbers: true,
  },
  {
    code: fatArrowFunction3,
    title: 'Functions',
    subtitle: 'Fat arrow function (anonymous inline definition)',
    lang: 'js',
    showNumbers: true,
    focus: '1[25:32],2,3[1]',
  },
  {
    code: objectDest1,
    title: 'Object destructuring',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
  },
  {
    code: objectDest2,
    title: 'Object destructuring',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
  },
  {
    code: objectDest3,
    title: 'Object destructuring',
    subtitle: 'Using the rest syntax',
    lang: 'js',
    showNumbers: true,
  },
  {
    code: objectSpread,
    title: 'Object spread',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
    focus: '7:10,12:16',
  },
  {
    code: arrayDest1,
    title: 'Array destructuring',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
  },
  {
    code: arrayDest2,
    title: 'Array destructuring',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
  },
  {
    code: arrayDest3,
    title: 'Array destructuring',
    subtitle: 'Using the rest syntax',
    lang: 'js',
    showNumbers: true,
  },
  {
    code: arraySpread,
    title: 'Array spread',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
  },
  {
    code: tern1,
    title: 'Ternary operator',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
  },
  {
    code: tern2,
    title: 'Ternary operator',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
  },
  {
    code: arrayMap,
    title: 'Mapping over arrays',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
  },
  {
    code: promise1,
    title: 'Promises',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
  },
  {
    code: promise2,
    title: 'Promises',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
  },
  {
    code: promise3,
    title: 'Promises',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
    focus: '3',
  },
  {
    code: promise3,
    title: 'Promises',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
    focus: '9',
  },
  {
    code: promise3,
    title: 'Promises',
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
    focus: '6',
  },
  {
    code: switchStatement,
    title: (
      <>
        Native <code>switch</code> statements 💩
      </>
    ),
    subtitle: undefined,
    lang: 'js',
    showNumbers: true,
    focus: undefined,
  },
];
